export const COUNTRIES = [
  { value: 'KR', label: '대한민국' },
  { value: 'CN', label: '중국' },
  { value: 'HK', label: '홍콩' },
  { value: 'SG', label: '싱가포르' },
  { value: 'JP', label: '일본' },
  { value: 'VN', label: '베트남' },
  { value: 'US', label: '미국' },
  { value: 'GB', label: '영국' },
  { value: 'DE', label: '독일' },
  { value: 'FR', label: '프랑스' },
  { value: 'AU', label: '호주' },
  { value: 'CA', label: '캐나다' },
  { value: 'IN', label: '인도' },
  { value: 'ID', label: '인도네시아' },
  { value: 'MY', label: '말레이시아' },
  { value: 'TH', label: '태국' },
  { value: 'PH', label: '필리핀' },
  { value: 'TW', label: '대만' },
  { value: 'OTHER', label: '기타' },
]
